[package]
name = "tcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
serde = {version = "1.0.219", features = ["derive"]}
serde_cbor = "0.11.2"
tokio = { version = "1.43.0", features = ["full"] }
